version: 2

project_name: 4sq-exports

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/riussi/4sq-exports/cmd.clientID={{.Env.FOURSQCLIENTID}}
      - -X github.com/riussi/4sq-exports/cmd.clientSecret={{.Env.FOURSQCLIENTSECRET}}
      - -X github.com/riussi/4sq-exports/cmd.commit={{.ShortCommit}}
      - -X github.com/riussi/4sq-exports/cmd.compiled={{.Date}}
      - -X github.com/riussi/4sq-exports/cmd.version={{.Version}}
    binary: 4sq-exports
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^example:'
      - '^docs:'
      - '^test:'
